WebApplication1/Models/MenuViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class MenuViewModel
    {
        public string Select { get; set; }
        public List<ParameterGame> Parameters { get; set; }
        public MenuViewModel()
        {
            Parameters = new List<ParameterGame>();
        }
    }

    public class ParameterGame
    {
        public string Name { get; set; }
        public IEnumerable<string> Values { get; set; }
    }
}

WebApplication1/Controllers/GameController.cs
using System.Data.Entity;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Entities;
using Microsoft.Owin.Security;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using WebApplication1.Models;
using System;

namespace WebApplication1.Controllers
{
    public class GameController : Controller
    {
        private int _itemPerPage = 6;
        private AppContext Context
        {
            get
            {
                return HttpContext.GetOwinContext().Get<AppContext>();
            }
        }
        // GET: Game
        public ActionResult Index(string genre, int page = 1)
        {
            var games = Context.Games.Include(m => m.ParameterValues.Select(n => n.ParameterName));
            //.Where(m => m.ParameterValues)
            GameViewModel result = new GameViewModel();
            result.Games = Context.Games
                //.Where(m => m.Genre == (genre??m.Genre))
                .OrderBy(m => m.GameId)
                .Skip((page - 1) * (_itemPerPage))
                .Take(_itemPerPage);
            result.CurrentPage = page;
            result.CurrentGenre = genre;
            result.TotalPage = games.Count() % _itemPerPage == 0 ? games.Count() / _itemPerPage : games.Count() / _itemPerPage + 1;
            return View(result);
        }
        public ActionResult IndexAjax(List<FilterData> result, int page=1)
        {
            List<Game> queryResult = Context.Games.ToList();
            if (result != null)
            {
                var qwe = new List<FilterData>();
                qwe.Add(new FilterData { Name = "genre", Value = "Шутер" });
                qwe.Add(new FilterData { Name = "operatingSystem", Value = "Mac OS X" });
                qwe.Add(new FilterData { Name = "genre", Value = "Экшен" });
                var groupResult = result.GroupBy(m => m.Name, m => m.Value);
                foreach (var name in groupResult)
                {
                    List<Game> resultByPropertyName = new List<Game>(); ;
                    foreach (var value in name)
                    {
                        var tempResult = Context.ParameterValues.Where(m => m.Name == value).SelectMany(n => n.Games).ToList();
                        resultByPropertyName = resultByPropertyName.Union(tempResult).ToList();
                    }
                    queryResult = queryResult.Intersect(resultByPropertyName).ToList();
                }
            }

            GameViewModel resultToView = new GameViewModel();
            resultToView.Games = queryResult
                .OrderBy(m => m.GameId)
                .Skip((page - 1) * (_itemPerPage))
                .Take(_itemPerPage);
            resultToView.CurrentPage = page;
            resultToView.CurrentGenre = "";
            resultToView.TotalPage = queryResult.Count() % _itemPerPage == 0 ? queryResult.Count() / _itemPerPage : queryResult.Count() / _itemPerPage + 1;
            return PartialView("Index", resultToView);
        }
    }
}

WebApplication1/Controllers/MenuController.cs
using Microsoft.AspNet.Identity.Owin;
using System.Data.Entity;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Entities;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class MenuController : Controller
    {
        private AppContext Context
        {
            get
            {
                return HttpContext.GetOwinContext().Get<AppContext>();
            }
        }
        public PartialViewResult Index(string genre)
        {
            MenuViewModel model = new MenuViewModel();
            var parametersNames = Context.ParameterNames.Select(m=>m.Name).ToList();
            foreach (var item in parametersNames)
            {
                model.Parameters.Add(new ParameterGame
                {
                    Name = item,
                    Values = Context.ParameterValues.Include(m => m.ParameterName).Where(n => n.ParameterName.Name == item).Select(b => b.Name).ToArray()
                });
            }
            model.Select = genre;
            return PartialView(model);
        }
    }
}

WebApplication1/Views/Menu/Index.cshtml
@model WebApplication1.Models.MenuViewModel
<div id="menu">
    <ul class="nav">
        <li class="active">
            @Html.ActionLink("Все жанры", "Index", "Game", null, new { @class = (Model.Select == null ? " selected" : "") })
        </li>
        @*@foreach (var item in Model.Genres)
            {
                <li>
                    @Html.ActionLink(item, "Index", "Game", new { genre = item }, new { @class = (Model.Select == item ? " selected" : "") })
                </li>
            }*@

        @foreach (var parameter in Model.Parameters)
        {
            <li>@parameter.Name</li>
            foreach (var value in parameter.Values)
            {
                <li>
                    <div class="filter-control" data-param ="@parameter.Name" data-value="@value">
                        <div class="filter-control-checkbox"></div>
                        <span class="filter-control-label">@value</span>
                    </div>
                </li>
            }
        }
    </ul>
</div>

<script>
    $(document).ready(function () {
        $(".filter-control").on('click', function (ecent) {
            event.preventDefault();
            if ($(this).hasClass("checked")) {
                $(this).removeClass("checked");
            }
            else {
                $(this).addClass("checked");
            }
            var checked = $(".checked");
            var result = new Array();
            for (var i = 0; i < checked.length; i++) {
                result.push({ name: $(checked[i]).attr('data-param'), value: $(checked[i]).attr('data-value')})
            }
            console.log(result)
            $.ajax({
                type: "POST",
                url: "@Url.RouteUrl(new { controller = "Game", action = "IndexAjax" })",
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(result),
                success: function(data) {
                    $("#content").html(data);
                }

            })
        })


    })
</script>