WebApplication1/Controllers/CartController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Data.Entity;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Entities;
using System.Data.Entity;

namespace WebApplication1.Controllers
{
    [Authorize(Roles ="User, Admin")]
    public class CartController : Controller
    {
        private AppUser CurrentUser
        {
            get
            {
               return UserManager.FindByEmail(HttpContext.User.Identity.Name);
            }
        }
        private AppUserManager UserManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<AppUserManager>();
            }
        }
        private AppContext Context
        {
            get
            {
                return HttpContext.GetOwinContext().Get<AppContext>();
            }
        }
        // GET: Cart
        public void AddToCart(int gameId)
        {
            AppUser user = CurrentUser;
            Cart cart = Context.Carts.Include(n=>n.CartLines).FirstOrDefault(m => m.UserId == user.Id);
            if (cart==null)
            {
                cart = new Cart
                {
                    UserId = user.Id
                };
                Context.Carts.Add(cart);
            }
            CartLine cartLine = cart.CartLines.FirstOrDefault(m => m.GameId == gameId&&m.CartId==cart.CartId);
            if (cartLine==null)
            {
                cartLine = new CartLine
                {
                    CartId = cart.CartId,
                    GameId = gameId,
                    Count = 1
                };
                cart.CartLines.Add(cartLine);
            }
            else
            {
                cartLine.Count++;
            }
            Context.SaveChanges();
        }
        public ActionResult Index()
        {
            AppUser user = CurrentUser;
            var games = Context.Games.ToList();
            Cart cart = Context.Carts.Include(x=>x.CartLines.Select(p=>p.Game)).FirstOrDefault(m => m.UserId == user.Id);


            return View(cart);
        }
        public PartialViewResult CartInfo()
        {
            return PartialView();
        }

    }
}

WebApplication1/Controllers/MenuController.cs
using Microsoft.AspNet.Identity.Owin;
using System.Data.Entity;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Entities;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class MenuController : Controller
    {
        private AppContext Context
        {
            get
            {
                return HttpContext.GetOwinContext().Get<AppContext>();
            }
        }
        public PartialViewResult Index(string genre)
        {
            MenuViewModel model = new MenuViewModel();
            var parametersNames = Context.ParameterNames.Select(m=>m.Name).ToList();
            foreach (var item in parametersNames)
            {
                model.Parameters.Add(new ParameterGame
                {
                    Name = item,
                    Values = Context.ParameterValues.Include(m => m.ParameterName).Where(n => n.ParameterName.Name == item).Select(b => b.Name).ToArray()
                });
            }
            model.Select = genre;
            return PartialView(model);
        }
    }
}

WebApplication1/Views/Shared/_GameInfo.cshtml
@model WebApplication1.Entities.Game
<div class="game-block row">
    <div class="col-sm-3">
        <img src="@Model.Cover" />
    </div>
    <div class="col-sm-7 game-name">@Model.Name</div>
    <div class="col-sm-2 game-buy">
        <p class="game-price">@Model.Price$</p>
        @using (Ajax.BeginForm("AddToCart", "Cart", new AjaxOptions {OnFailure="Fail"}))
        {
            @Html.HiddenFor(m => m.GameId)
            <input class="btn btn-success" type="submit" name="@Model.GameId" value="Купить" />
        }
    </div>
</div>

<script>
    function Fail(data, e) {
        alert("Для добавления товаров в корзину необходимо авторизоваться")
        $(location).attr('href', "/Account/Index");
        console.log(data);
    }
</script>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/my-change-bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <script src="~/scripts/jquery-3.1.0.min.js"></script>
    <script src="~/scripts/jquery.unobtrusive-ajax.min.js"></script>

</head>
<body>
    <div class="container">
        <div class="navbar navbar-default">
            <div class="container">
                <div class="navbar-header">
                    @Html.ActionLink("MySite", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        @Html.Action("LoginInfo", "Account")
                    </ul>
                </div>
            </div>
        </div>
        <div class="container body-content">
            <div class="row">
                <div class="col-xs-3">@Html.Action("Index", "Menu")</div>
                <div id="content" class="col-xs-9">@RenderBody()</div>
            </div>
            <hr />
        </div>
    </div>
</body>
</html>

WebApplication1/Views/Shared/_LoginInfo.cshtml
@model System.Security.Principal.IPrincipal

@if (Model.Identity.IsAuthenticated)
{
    <li>@Html.ActionLink("Корзина", "", "Cart")</li>
    <li class="navbar-text"><span>@Model.Identity.Name</span></li>
    <li>@Html.ActionLink("Выйти","Logout","Account")</li>
}
else
{
    <li>@Html.ActionLink("Войти", "Index", "Account", new { returnUrl = Request.Url.PathAndQuery },null)</li>
    <li>@Html.ActionLink("Зарегистрироваться", "Index", "Account", new { returnUrl = Request.Url.PathAndQuery }, null)</li>
}